export const inchWorm = '#ABDF75'
export const black = '#000'
export const white = '#fff'
export const nyanza = '#D6F9DD'
export const steelTeal = '#558C8C'
export const darkGray = '#111111'
export const lightGray = '#D1D1D1'
export const orange = '#FFAC40'